# Generated by Django 6.0.5 on 2026-05-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pitcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="投手名")),
                ("team", models.CharField(max_length=100, verbose_name="所属球団")),
                (
                    "innings_pitched",
                    models.FloatField(default=0, verbose_name="投球回"),
                ),
                ("earned_runs", models.IntegerField(default=0, verbose_name="自責点")),
                ("saves", models.IntegerField(default=0, verbose_name="セーブ数")),
            ],
        ),
    ]
