# Generated by Django 6.0.5 on 2026-05-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitcher",
            name="team",
            field=models.CharField(
                choices=[
                    ("巨人", "読売ジャイアンツ"),
                    ("阪神", "阪神タイガース"),
                    ("広島", "広島東洋カープ"),
                    ("中日", "中日ドラゴンズ"),
                    ("DeNA", "横浜DeNAベイスターズ"),
                    ("ヤクルト", "東京ヤクルトスワローズ"),
                    ("ソフトバンク", "福岡ソフトバンクホークス"),
                    ("ロッテ", "千葉ロッテマリーンズ"),
                    ("西武", "埼玉西武ライオンズ"),
                    ("楽天", "東北楽天ゴールデンイーグルス"),
                    ("オリックス", "オリックス・バファローズ"),
                    ("日本ハム", "北海道日本ハムファイターズ"),
                ],
                max_length=100,
                verbose_name="所属球団",
            ),
        ),
    ]
