# Generated by Django 6.0.5 on 2026-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_pitcher_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitcher",
            name="holds",
            field=models.IntegerField(default=0, verbose_name="ホールド"),
        ),
        migrations.AddField(
            model_name="pitcher",
            name="losses",
            field=models.IntegerField(default=0, verbose_name="負け"),
        ),
        migrations.AddField(
            model_name="pitcher",
            name="wins",
            field=models.IntegerField(default=0, verbose_name="勝ち"),
        ),
        migrations.AlterField(
            model_name="pitcher",
            name="saves",
            field=models.IntegerField(default=0, verbose_name="セーブ"),
        ),
    ]
