# Generated by Django 6.0.5 on 2026-05-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_pitcher_holds_pitcher_losses_pitcher_wins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitcher",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="お気に入り"),
        ),
    ]
